version: '3.4'
services:
  db:
    image: lucioslv/mysql-coffe-with-ci-cd
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: coffe_with_ci_cd
    ports:
      - "3306:3306"
    networks:
      - coffe-network
  coffe-with-spring-boot:
    image: lucioslv/coffe-with-spring-boot
    restart: always
    build: ./CoffeWithSpring
    working_dir: /CoffeWithSpring
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./CoffeWithSpring:/CoffeWithSpring
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - coffe-network
networks: 
    coffe-network:
        driver: bridge