version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: coffe_with_ci_cd
    ports:
      - "3306:3306"
    networks:
      - coffe-network
  coffe-with-spring-boot:
    image: coffe-with-spring-boot
    restart: always
    build: ./CoffeWithSpring
    working_dir: /CoffeWithSpring
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - coffe-network
networks: 
    coffe-network:
        driver: bridge